# docker-compose.backend.yml
version: '3.8'
services:
  mariadb:
    image: mariadb:10.11
    container_name: hospital-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-1234}
      MYSQL_DATABASE: hospital
      MYSQL_USER: hospitaluser
      MYSQL_PASSWORD: ${DB_PASSWORD:-hospitalpass}
    ports:
      - "3500:3306"
    volumes:
      - /opt/hospital/data:/var/lib/mysql
    command: --port=3500
    restart: unless-stopped
    networks:
      - hospital-network

  backend:
    image: hospital-backend:latest
    container_name: hospital-backend
    ports:
      - "8888:8888"
    environment:
      - DB_URL=jdbc:mariadb://mariadb:3500/hospital_api_db
      - DB_USERNAME=hospitaluser
      - DB_PASSWORD=${DB_PASSWORD:-hospitalpass}
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - hospital-network

networks:
  hospital-network:
    driver: bridge
