version: '3.8'
services:
  mariadb:
    image: mariadb:10.11
    container_name: hospital-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hospital_api_db
      MYSQL_USER: hospitaluser
      MYSQL_PASSWORD: hospitalpass
    ports:
      - "3500:3306"
    volumes:
      - /opt/hospital/data:/var/lib/mysql
    command: --port=3500
    restart: unless-stopped

  backend:
    image: hospital-backend:latest
    container_name: hospital-backend
    ports:
      - "8888:8888"
    environment:
      - DB_URL=jdbc:mariadb://mariadb:3500/hospital_api_db
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - mariadb
    restart: unless-stopped

# frontend 섹션 제거
