version: '3.8'
services:
  mariadb:
    image: mariadb:10.11  # 더 최신 버전 권장
    container_name: hospital-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-1234}
      MYSQL_DATABASE: hospital_api_db
      MYSQL_USER: hospitaluser
      MYSQL_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "3500:3500"  # 외부:내부 모두 3500
    volumes:
      - /opt/hospital/data:/var/lib/mysql
    command: --port=3500
    restart: unless-stopped
    networks:
      - hospital-network
      
  backend:
    image: hospital-backend:latest
    container_name: hospital-backend
    ports:
      - "8888:8888"
    environment:
      - DB_URL=jdbc:mariadb://mariadb:3500/hospital_api_db  # 3500 유지
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD:-1234}
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - hospital-network
      
  frontend:
    image: hospital-frontend:latest
    container_name: hospital-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hospital-network
      
networks:
  hospital-network:
    driver: bridge
