version: '3.8' 
services:
  mariadb:
    image: mariadb:10.11
    container_name: hospital-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hospital_api_db
      MYSQL_USER: hospitaluser
      MYSQL_PASSWORD: hospitalpass
    ports:
      - "3500:3500"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --port=3500
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3500", "-u", "root", "-p1234"]
      timeout: 20s
      retries: 10
      interval: 30s
    networks:
      - hospital-network
    restart: unless-stopped
    
  backend:
    image: hospital-backend:latest  # build 대신 image 사용 (GitHub Actions에서 빌드한 이미지)
    container_name: hospital-backend
    ports:
      - "8888:8888"
    environment:
      - DB_URL=jdbc:mariadb://mariadb:3500/hospital_api_db
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - hospital-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      timeout: 30s
      retries: 5
      interval: 30s
      start_period: 60s

volumes:
  mariadb_data:
networks:
  hospital-network:
    driver: bridge
