version: '3.8'
services:
  mariadb:
    image: mariadb:10.6
    container_name: hospital-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hospital_api_db  
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3500:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --port=3500
    networks:
      - hospital-network

  backend:
    build: ./hospital_main
    container_name: hospital-backend
    ports:
      - "8888:8888"
    environment:
      - DB_URL=jdbc:mariadb://mariadb:3500/hospital
      - DB_USERNAME=hospitaluser
      - DB_PASSWORD=hospitalpass
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - mariadb
    networks:
      - hospital-network

  frontend:
    build: ./frontend
    container_name: hospital-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - hospital-network

volumes:
  mariadb_data:

networks:
  hospital-network:
    driver: bridge
