name: Deploy Hospital Project to EC2

on:
  push:
    branches: [ main ]

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Backend Image
      run: |
        cd hospital_main
        docker build -t hospital-backend:${{ github.sha }} .
        docker tag hospital-backend:${{ github.sha }} hospital-backend:latest

    - name: Build Frontend Image
      run: |
        cd frontend
        # GitHub Secrets를 .env.production으로 생성
        echo "VITE_API_BASE_URL=http://${{ secrets.EC2_HOST }}:8888" > .env.production
        echo "VITE_GOOGLE_TTS_API_KEY=${{ secrets.VITE_GOOGLE_TTS_API_KEY }}" >> .env.production
        echo "VITE_KAKAO_REST_API_KEY=${{ secrets.VITE_KAKAO_REST_API_KEY }}" >> .env.production
        echo "VITE_KAKAO_MAP_KEY=${{ secrets.VITE_KAKAO_MAP_KEY }}" >> .env.production
        docker build -t hospital-frontend:${{ github.sha }} .
        docker tag hospital-frontend:${{ github.sha }} hospital-frontend:latest

    - name: Save Docker Images
      run: |
        docker save hospital-backend:latest | gzip > backend.tar.gz
        docker save hospital-frontend:latest | gzip > frontend.tar.gz

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: "backend.tar.gz,frontend.tar.gz,docker-compose.prod.yml,deploy.sh"
        target: "/home/ec2-user/"

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Docker 이미지 로드
          docker load < /home/ec2-user/backend.tar.gz
          docker load < /home/ec2-user/frontend.tar.gz
          
          # 환경 변수 설정
          export IMAGE_TAG=latest
          export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          export DB_ROOT_PASSWORD="${{ secrets.DB_ROOT_PASSWORD }}"
          
          # 배포 스크립트 실행
          chmod +x /home/ec2-user/deploy.sh
          /home/ec2-user/deploy.sh
          
          # 파일 정리
          rm -f /home/ec2-user/*.tar.gz
